CREATE DATABASE IF NOT EXISTS `${DB_NAME}`;
CREATE USER IF NOT EXISTS '${MYSQL_USER}' @'%' IDENTIFIED WITH caching_sha2_password BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON `${DB_NAME}`.* TO '${MYSQL_USER}' @'%';
FLUSH PRIVILEGES;